services:
  php.unit.tool.executor:
    class: Module\PhpUnit\Service\PhpUnitToolExecutor
    public: false
    arguments:
      - "@console.output"
      - "@php.unit.processor"
      - "@php.unit.randomizer.processor"