services:
  _defaults:
    public: true
  PhpGitHooks\Module\Files\Contract\Query\ComposerFilesExtractorHandler:
    tags:
      - { name: bruli.query_handler, handles: \PhpGitHooks\Module\Files\Contract\Query\ComposerFilesExtractor }
  PhpGitHooks\Module\Files\Contract\Query\JsonFilesExtractorHandler:
    tags:
      - { name: bruli.query_handler, handles: \PhpGitHooks\Module\Files\Contract\Query\JsonFilesExtractor }
  PhpGitHooks\Module\Files\Contract\Query\PhpFilesExtractorHandler:
    tags:
      - { name: bruli.query_handler, handles: \PhpGitHooks\Module\Files\Contract\Query\PhpFilesExtractor }

  composer.files.extractor.query.handler: '@PhpGitHooks\Module\Files\Contract\Query\ComposerFilesExtractorHandler'
  json.files.extractor.query.handler: '@PhpGitHooks\Module\Files\Contract\Query\JsonFilesExtractorHandler'
  php.files.extractor.query.handler: '@PhpGitHooks\Module\Files\Contract\Query\PhpFilesExtractorHandler'
