services:
  composer.tool.command.handler:
    class: PhpGitHooks\Module\Composer\Contract\CommandHandler\ComposerToolCommandHandler
    arguments: ["@composer.tool"]
    tags:
      - { name: command_handler, handles: \PhpGitHooks\Module\Composer\Contract\Command\ComposerToolCommand }
