services:
  _defaults:
    public: true
  PhpGitHooks\Module\PhpCs\Contract\Command\PhpCsToolHandler:
    arguments:
      - "@console.output"
      - "@php.cs.tool.processor"
    tags:
      - { name: bruli.command_handler, handles: \PhpGitHooks\Module\PhpCs\Contract\Command\PhpCsTool }

  php.tool.command.handler: '@PhpGitHooks\Module\PhpCs\Contract\Command\PhpCsToolHandler'