services:
  php.cs.tool:
    class: PhpGitHooks\Module\PhpCs\Service\PhpCsTool
    public: false
    arguments:
      - "@php.cs.tool.executor"
      - "@query.bus"
  php.cs.tool.executor:
    class: PhpGitHooks\Module\PhpCs\Service\PhpCsToolExecutor
    public: false
    arguments:
      - "@console.output"
      - "@php.cs.tool.processor"
