imports:
  - { resource: "./../../src/PhpGitHooks/Module/Configuration/Infrastructure/DependencyInjection/" }
  - { resource: "./../../src/PhpGitHooks/Module/Git/Infrastructure/DependencyInjection/" }
  - { resource: "./../../src/PhpGitHooks/Module/Composer/Infrastructure/DependencyInjection/" }
  - { resource: "./../../src/PhpGitHooks/Module/JsonLint/Infrastructure/DependencyInjection/" }
  - { resource: "./../../src/PhpGitHooks/Module/PhpLint/Infrastructure/DependencyInjection/" }
  - { resource: "./../../src/PhpGitHooks/Module/PhpCs/Infrastructure/DependencyInjection/" }
  - { resource: "./../../src/PhpGitHooks/Module/PhpCsFixer/Infrastructure/DependencyInjection/" }
  - { resource: "./../../src/PhpGitHooks/Module/PhpUnit/Infrastructure/DependencyInjection/" }
  - { resource: "./../../src/PhpGitHooks/Module/Files/Infrastructure/DependencyInjection/" }
  - { resource: "./../../src/PhpGitHooks/Module/PhpMd/Infrastructure/DependencyInjection/" }
services:
    _defaults:
      public: true
    Symfony\Component\Console\Output\ConsoleOutput:
    PhpGitHooks\Infrastructure\Tool\ToolPathFinder:

    console.output: '@Symfony\Component\Console\Output\ConsoleOutput'
    tool.path.finder: '@PhpGitHooks\Infrastructure\Tool\ToolPathFinder'
