services:
  configuration.processor:
    class: PhpGitHooks\Module\Configuration\Service\ConfigurationProcessor
    public: false
    arguments:
      - "@configuration.file.reader"
      - "@pre.commit.processor"
      - "@commit.msg.processor"
      - "@configuration.file.writer"
      - "@hook.copier"
      - "@pre.push.processor"
  configuration.data.finder:
    class: PhpGitHooks\Module\Configuration\Service\ConfigurationDataFinder
    public: false
    arguments: ["@configuration.file.reader"]
  pre.commit.processor:
    class: PhpGitHooks\Module\Configuration\Service\PreCommitProcessor
    public: false
    arguments:
      - "@php.unit.guard.coverage.configurator"
  commit.msg.processor:
    class: PhpGitHooks\Module\Configuration\Service\CommitMsgProcessor
    public: false
    arguments: ["@console.output"]
  pre.push.processor:
    class: PhpGitHooks\Module\Configuration\Service\PrePushProcessor
    public: false
    arguments:
      - "@php.unit.guard.coverage.configurator"
  php.unit.guard.coverage.configurator:
    class: PhpGitHooks\Module\Configuration\Service\PhpUnitGuardCoverageConfigurator
    public: false
    arguments: ["@php.unit.guard.coverage.gitignore.cofigurator"]
  php.unit.guard.coverage.gitignore.cofigurator:
    class: PhpGitHooks\Module\Configuration\Service\PhpGuardCoverageGitIgnoreConfigurator
    public: false
    arguments:
      - "@query.bus"
      - "@command.bus"
