services:
  _defaults:
    public: true
  PhpGitHooks\Module\Configuration\Service\PreCommitProcessor:
    public: false
    arguments:
      - "@php.unit.guard.coverage.configurator"
  PhpGitHooks\Module\Configuration\Service\CommitMsgProcessor:
    public: false
    arguments: ["@console.output"]
  PhpGitHooks\Module\Configuration\Service\PrePushProcessor:
    public: false
    arguments:
      - "@php.unit.guard.coverage.configurator"
  PhpGitHooks\Module\Configuration\Service\PhpUnitGuardCoverageConfigurator:
    public: false
    arguments: ["@php.unit.guard.coverage.gitignore.configurator"]
  PhpGitHooks\Module\Configuration\Service\PhpGuardCoverageGitIgnoreConfigurator:
    public: false
    arguments:
      - "@bruli.query.bus"
      - "@bruli.command.bus"

  pre.commit.processor: '@PhpGitHooks\Module\Configuration\Service\PreCommitProcessor'
  commit.msg.proccessor: '@PhpGitHooks\Module\Configuration\Service\CommitMsgProcessor'
  pre.push.processor: '@PhpGitHooks\Module\Configuration\Service\PrePushProcessor'
  php.unit.guard.coverage.configurator: '@PhpGitHooks\Module\Configuration\Service\PhpUnitGuardCoverageConfigurator'
  php.unit.guard.coverage.gitignore.configurator: '@PhpGitHooks\Module\Configuration\Service\PhpGuardCoverageGitIgnoreConfigurator'
