services:
  configuration.processor.handler:
    class: PhpGitHooks\Module\Configuration\Contract\Command\ConfigurationProcessorHandler
    arguments:
          - "@configuration.file.reader"
          - "@pre.commit.processor"
          - "@commit.msg.processor"
          - "@configuration.file.writer"
          - "@hook.copier"
          - "@pre.push.processor"
    tags:
      - { name: bruli.command_handler, handles: \PhpGitHooks\Module\Configuration\Contract\Command\ConfigurationProcessorCommand}
  configuration.data.finder.query.handler:
    class: PhpGitHooks\Module\Configuration\Contract\QueryHandler\ConfigurationDataFinderQueryHandler
    arguments: ["@configuration.data.finder"]
    tags:
      - { name: bruli.query_handler, handles: \PhpGitHooks\Module\Configuration\Contract\Query\ConfigurationDataFinderQuery }
