services:
  _defaults:
    public: true
  PhpGitHooks\Module\PhpCsFixer\Contract\Command\PhpCsFixerToolHandler:
    arguments:
      - "@console.output"
      - "@php.cs.fixer.tool.processor"
    tags:
      - { name: bruli.command_handler, handles: \PhpGitHooks\Module\PhpCsFixer\Contract\Command\PhpCsFixerTool }

  phpcsfixer.tool.command.handler: '@PhpGitHooks\Module\PhpCsFixer\Contract\Command\PhpCsFixerToolHandler'