services:
  jsonlint.tool:
    class: PhpGitHooks\Module\JsonLint\Service\JsonLintTool
    public: false
    arguments:
      - "@jsonlint.tool.executor"
      - "@query.bus"
  jsonlint.tool.executor:
    class: PhpGitHooks\Module\JsonLint\Service\JsonLintToolExecutor
    arguments:
      - "@jsonlint.processor"
      - "@console.output"
