services:
  _defaults:
    public: true
  PhpGitHooks\Module\JsonLint\Service\JsonLintToolExecutor:
    arguments:
      - "@jsonlint.processor"
      - "@console.output"

  jsonlint.tool.executor: '@PhpGitHooks\Module\JsonLint\Service\JsonLintToolExecutor'
