services:
  _defaults:
    public: true
  PhpGitHooks\Module\JsonLint\Contract\Command\JsonLintToolHandler:
    arguments:
      - "@jsonlint.tool.executor"
      - "@bruli.query.bus"
    tags:
     - { name: bruli.command_handler, handles: \PhpGitHooks\Module\JsonLint\Contract\Command\JsonLintTool }

  jsonlint.tool.command.handler: '@PhpGitHooks\Module\JsonLint\Contract\Command\JsonLintToolHandler'
