services:
  _defaults:
    public: true
  PhpGitHooks\Module\Git\Contract\Command\PreCommitToolHandler:
    arguments:
          - "@console.output"
          - "@files.commited.extractor"
          - "@bruli.query.bus"
          - "@bruli.command.bus"
          - "@tool.title.output.writer"
    tags:
      - { name: bruli.command_handler, handles: \PhpGitHooks\Module\Git\Contract\Command\PreCommitTool}
  PhpGitHooks\Module\Git\Contract\Command\CommitMsgHandler:
    arguments:
          - "@merge.validator"
          - "@bruli.query.bus"
          - "@commit.message.finder"
    tags:
      - { name: bruli.command_handler, handles: \PhpGitHooks\Module\Git\Contract\Command\CommitMsg }
  PhpGitHooks\Module\Git\Contract\Command\PrePushToolHandler:
    arguments:
      - "@bruli.query.bus"
      - "@pre.push.original.executor"
      - "@console.output"
      - "@bruli.command.bus"
    tags:
      - { name: bruli.command_handler, handles: \PhpGitHooks\Module\Git\Contract\Command\PrePushTool }
  PhpGitHooks\Module\Git\Contract\Command\GitIgnoreWriterHandler:
    arguments: ["@gitignore.file.writer"]
    tags:
      - { name: bruli.command_handler, handles: \PhpGitHooks\Module\Git\Contract\Command\GitIgnoreWriter }
  PhpGitHooks\Module\Git\Contract\Query\GitIgnoreExtractorHandler:
    arguments: ["@gitignore.file.reader"]
    tags:
      - { name: bruli.query_handler, handles: \PhpGitHooks\Module\Git\Contract\Query\GitIgnoreExtractor }

  pre.commit.tool.command.handler: '@PhpGitHooks\Module\Git\Contract\Command\PreCommitToolHandler'
  commit.msg.handler: '@PhpGitHooks\Module\Git\Contract\Command\CommitMsgHandler'
  pre.push.tool.command.handler: '@PhpGitHooks\Module\Git\Contract\Command\PrePushToolHandler'
  gitignore.writer.command.handler: '@PhpGitHooks\Module\Git\Contract\Command\GitIgnoreWriterHandler'
  gitignore.extractor.query.handler: '@PhpGitHooks\Module\Git\Contract\Query\GitIgnoreExtractorHandler'
