services:
  pre.commit.tool.command.handler:
    class: PhpGitHooks\Module\Git\Contract\Command\PreCommitToolHandler
    arguments:
          - "@console.output"
          - "@files.commited.extractor"
          - "@bruli.query.bus"
          - "@bruli.command.bus"
          - "@tool.title.output.writer"
    tags:
      - { name: bruli.command_handler, handles: \PhpGitHooks\Module\Git\Contract\Command\PreCommitTool}
  commit.msg.handler:
    class: PhpGitHooks\Module\Git\Contract\Command\CommitMsgHandler
    arguments:
          - "@merge.validator"
          - "@bruli.query.bus"
          - "@commit.message.finder"
    tags:
      - { name: bruli.command_handler, handles: \PhpGitHooks\Module\Git\Contract\Command\CommitMsg }
  pre.push.tool.command.handler:
    class: PhpGitHooks\Module\Git\Contract\CommandHandler\PrePushToolCommandHandler
    arguments: ["@pre.push.tool"]
    tags:
      - { name: bruli.command_handler, handles: \PhpGitHooks\Module\Git\Contract\Command\PrePushToolCommand }
  gitignore.writer.command.handler:
    class: PhpGitHooks\Module\Git\Contract\Command\GitIgnoreWriterHandler
    arguments: ["@gitignore.file.writer"]
    tags:
      - { name: bruli.command_handler, handles: \PhpGitHooks\Module\Git\Contract\Command\GitIgnoreWriter }
  gitignore.extractor.query.handler:
    class: PhpGitHooks\Module\Git\Contract\QueryHandler\GitIgnoreExtractorQueryHandler
    arguments: ["@gitignore.extractor"]
    tags:
      - { name: bruli.query_handler, handles: \PhpGitHooks\Module\Git\Contract\Query\GitIgnoreExtractorQuery }
