services:
  _defaults:
    public: true
  PhpGitHooks\Module\Git\Infrastructure\Files\FilesCommittedExtractor:
    public: false

  files.commited.extractor: '@PhpGitHooks\Module\Git\Infrastructure\Files\FilesCommittedExtractor'
