services:
  _defaults:
    public: true
  strict.coverage.tool:
    class: PhpGitHooks\Module\PhpUnit\Service\StrictCoverageTool
    public: false
    arguments:
      - "@strict.coverage.processor"
      - "@console.output"


