services:
  _defaults:
    public: true
  PhpGitHooks\Module\PhpUnit\Infrastructure\Tool\PhpUnitProcessor:
    public: false
    arguments:
      - "@console.output"
      - "@tool.path.finder"
  PhpGitHooks\Module\PhpUnit\Infrastructure\Tool\PhpUnitRandomizerProcessor:
    public: false
    arguments:
      - "@console.output"
      - "@tool.path.finder"
  PhpGitHooks\Module\PhpUnit\Infrastructure\Tool\StrictCoverageProcessor:
    public: false
    arguments: ["@tool.path.finder"]
  PhpGitHooks\Module\PhpUnit\Infrastructure\Tool\GuardCoverageFileReader:
    public: false
  PhpGitHooks\Module\PhpUnit\Infrastructure\Tool\GuardCoverageFileWriter:
    public: false

  php.unit.processor: '@PhpGitHooks\Module\PhpUnit\Infrastructure\Tool\PhpUnitProcessor'
  php.unit.randomizer.processor: '@PhpGitHooks\Module\PhpUnit\Infrastructure\Tool\PhpUnitRandomizerProcessor'
  strict.coverage.processor: '@PhpGitHooks\Module\PhpUnit\Infrastructure\Tool\StrictCoverageProcessor'
  guard.coverage.file.reader: '@PhpGitHooks\Module\PhpUnit\Infrastructure\Tool\GuardCoverageFileReader'
  guard.coverage.file.writer: '@PhpGitHooks\Module\PhpUnit\Infrastructure\Tool\GuardCoverageFileWriter'
